// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/entities/pin.proto

package entitiesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pin represents a pin on the map (composed from posts + posts_location)
type Pin struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content   string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                       // Title/description of the pin
	Location  *Location              `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`                     // Geographic location
	CreatedAt int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	// API-only fields (joined/computed from database)
	Author        *User `protobuf:"bytes,7,opt,name=author,proto3,oneof" json:"author,omitempty"`                            // Joined from users table
	CommentCount  int32 `protobuf:"varint,8,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"` // Computed from posts with parent_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pin) Reset() {
	*x = Pin{}
	mi := &file_v1_entities_pin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_v1_entities_pin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_v1_entities_pin_proto_rawDescGZIP(), []int{0}
}

func (x *Pin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pin) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Pin) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Pin) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Pin) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Pin) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Pin) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Pin) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

// Location represents geographic coordinates
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`       // Latitude in decimal degrees
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`     // Longitude in decimal degrees
	Altitude      *float64               `protobuf:"fixed64,3,opt,name=altitude,proto3,oneof" json:"altitude,omitempty"` // Altitude in meters (optional)
	Geohash       *string                `protobuf:"bytes,4,opt,name=geohash,proto3,oneof" json:"geohash,omitempty"`     // Geohash for proximity queries
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_v1_entities_pin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_v1_entities_pin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_v1_entities_pin_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAltitude() float64 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

func (x *Location) GetGeohash() string {
	if x != nil && x.Geohash != nil {
		return *x.Geohash
	}
	return ""
}

// Comment represents a comment on a pin or reply to another comment
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      *string                `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"` // For nested replies (NULL for direct pin comments)
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`   // Unix timestamp
	Author        *User                  `protobuf:"bytes,6,opt,name=author,proto3,oneof" json:"author,omitempty"`                     // Joined from users table
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_v1_entities_pin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_entities_pin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_v1_entities_pin_proto_rawDescGZIP(), []int{2}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Comment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Comment) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

var File_v1_entities_pin_proto protoreflect.FileDescriptor

const file_v1_entities_pin_proto_rawDesc = "" +
	"\n" +
	"\x15v1/entities/pin.proto\x12\x0fapi.v1.entities\x1a\x16v1/entities/user.proto\"\xa1\x02\n" +
	"\x03Pin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x125\n" +
	"\blocation\x18\x04 \x01(\v2\x19.api.v1.entities.LocationR\blocation\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x122\n" +
	"\x06author\x18\a \x01(\v2\x15.api.v1.entities.UserH\x00R\x06author\x88\x01\x01\x12#\n" +
	"\rcomment_count\x18\b \x01(\x05R\fcommentCountB\t\n" +
	"\a_author\"\x9d\x01\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\baltitude\x18\x03 \x01(\x01H\x00R\baltitude\x88\x01\x01\x12\x1d\n" +
	"\ageohash\x18\x04 \x01(\tH\x01R\ageohash\x88\x01\x01B\v\n" +
	"\t_altitudeB\n" +
	"\n" +
	"\b_geohash\"\xda\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12 \n" +
	"\tparent_id\x18\x04 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x122\n" +
	"\x06author\x18\x06 \x01(\v2\x15.api.v1.entities.UserH\x01R\x06author\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\t\n" +
	"\a_authorBOZMgithub.com/radjathaher/alunalun/api/internal/protocgen/v1/entities;entitiesv1b\x06proto3"

var (
	file_v1_entities_pin_proto_rawDescOnce sync.Once
	file_v1_entities_pin_proto_rawDescData []byte
)

func file_v1_entities_pin_proto_rawDescGZIP() []byte {
	file_v1_entities_pin_proto_rawDescOnce.Do(func() {
		file_v1_entities_pin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_entities_pin_proto_rawDesc), len(file_v1_entities_pin_proto_rawDesc)))
	})
	return file_v1_entities_pin_proto_rawDescData
}

var file_v1_entities_pin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_entities_pin_proto_goTypes = []any{
	(*Pin)(nil),      // 0: api.v1.entities.Pin
	(*Location)(nil), // 1: api.v1.entities.Location
	(*Comment)(nil),  // 2: api.v1.entities.Comment
	(*User)(nil),     // 3: api.v1.entities.User
}
var file_v1_entities_pin_proto_depIdxs = []int32{
	1, // 0: api.v1.entities.Pin.location:type_name -> api.v1.entities.Location
	3, // 1: api.v1.entities.Pin.author:type_name -> api.v1.entities.User
	3, // 2: api.v1.entities.Comment.author:type_name -> api.v1.entities.User
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_entities_pin_proto_init() }
func file_v1_entities_pin_proto_init() {
	if File_v1_entities_pin_proto != nil {
		return
	}
	file_v1_entities_user_proto_init()
	file_v1_entities_pin_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_entities_pin_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_entities_pin_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_entities_pin_proto_rawDesc), len(file_v1_entities_pin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_entities_pin_proto_goTypes,
		DependencyIndexes: file_v1_entities_pin_proto_depIdxs,
		MessageInfos:      file_v1_entities_pin_proto_msgTypes,
	}.Build()
	File_v1_entities_pin_proto = out.File
	file_v1_entities_pin_proto_goTypes = nil
	file_v1_entities_pin_proto_depIdxs = nil
}
