// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/service/auth.proto

package servicev1

import (
	entities "github.com/ckrwl/alunalun/api/gen/api/v1/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckUsernameRequest checks availability
type CheckUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameRequest) Reset() {
	*x = CheckUsernameRequest{}
	mi := &file_v1_service_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameRequest) ProtoMessage() {}

func (x *CheckUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameRequest.ProtoReflect.Descriptor instead.
func (*CheckUsernameRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// CheckUsernameResponse returns availability
type CheckUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional reason if not available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameResponse) Reset() {
	*x = CheckUsernameResponse{}
	mi := &file_v1_service_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameResponse) ProtoMessage() {}

func (x *CheckUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameResponse.ProtoReflect.Descriptor instead.
func (*CheckUsernameResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUsernameResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckUsernameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// InitAnonymousRequest creates anonymous session
type InitAnonymousRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAnonymousRequest) Reset() {
	*x = InitAnonymousRequest{}
	mi := &file_v1_service_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAnonymousRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAnonymousRequest) ProtoMessage() {}

func (x *InitAnonymousRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAnonymousRequest.ProtoReflect.Descriptor instead.
func (*InitAnonymousRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_auth_proto_rawDescGZIP(), []int{2}
}

func (x *InitAnonymousRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// InitAnonymousResponse returns anonymous token
type InitAnonymousResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                          // JWT with no expiration
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Server-generated UUID
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                    // Confirmed username
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitAnonymousResponse) Reset() {
	*x = InitAnonymousResponse{}
	mi := &file_v1_service_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitAnonymousResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitAnonymousResponse) ProtoMessage() {}

func (x *InitAnonymousResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitAnonymousResponse.ProtoReflect.Descriptor instead.
func (*InitAnonymousResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_auth_proto_rawDescGZIP(), []int{3}
}

func (x *InitAnonymousResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *InitAnonymousResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitAnonymousResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// AuthenticateRequest for provider-based auth
type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                          // "google", "magic_link", etc
	Credential    string                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`                      // ID token, magic token, etc
	SessionId     *string                `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"` // For migration from anonymous
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_v1_service_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticateRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AuthenticateRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *AuthenticateRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

// AuthenticateResponse returns auth token
type AuthenticateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Token           string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT with 1hr expiration
	User            *entities.User         `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	SessionMigrated bool                   `protobuf:"varint,3,opt,name=session_migrated,json=sessionMigrated,proto3" json:"session_migrated,omitempty"` // If session_id was provided and migrated
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_v1_service_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenticateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticateResponse) GetUser() *entities.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthenticateResponse) GetSessionMigrated() bool {
	if x != nil {
		return x.SessionMigrated
	}
	return false
}

// RefreshTokenRequest refreshes expired JWT
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiredToken  string                 `protobuf:"bytes,1,opt,name=expired_token,json=expiredToken,proto3" json:"expired_token,omitempty"` // The expired JWT to refresh
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_v1_service_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetExpiredToken() string {
	if x != nil {
		return x.ExpiredToken
	}
	return ""
}

// RefreshTokenResponse returns new token
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // New JWT with 1hr expiration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_v1_service_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_v1_service_auth_proto protoreflect.FileDescriptor

const file_v1_service_auth_proto_rawDesc = "" +
	"\n" +
	"\x15v1/service/auth.proto\x12\x0eapi.v1.service\x1a\x16v1/entities/user.proto\x1a google/protobuf/field_mask.proto\"2\n" +
	"\x14CheckUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"O\n" +
	"\x15CheckUsernameResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x14InitAnonymousRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"h\n" +
	"\x15InitAnonymousResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"\x84\x01\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\x12\"\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tH\x00R\tsessionId\x88\x01\x01B\r\n" +
	"\v_session_id\"\x82\x01\n" +
	"\x14AuthenticateResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.api.v1.entities.UserR\x04user\x12)\n" +
	"\x10session_migrated\x18\x03 \x01(\bR\x0fsessionMigrated\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rexpired_token\x18\x01 \x01(\tR\fexpiredToken\",\n" +
	"\x14RefreshTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xff\x02\n" +
	"\vAuthService\x12\\\n" +
	"\rCheckUsername\x12$.api.v1.service.CheckUsernameRequest\x1a%.api.v1.service.CheckUsernameResponse\x12\\\n" +
	"\rInitAnonymous\x12$.api.v1.service.InitAnonymousRequest\x1a%.api.v1.service.InitAnonymousResponse\x12Y\n" +
	"\fAuthenticate\x12#.api.v1.service.AuthenticateRequest\x1a$.api.v1.service.AuthenticateResponse\x12Y\n" +
	"\fRefreshToken\x12#.api.v1.service.RefreshTokenRequest\x1a$.api.v1.service.RefreshTokenResponseB<Z:github.com/ckrwl/alunalun/api/gen/api/v1/service;servicev1b\x06proto3"

var (
	file_v1_service_auth_proto_rawDescOnce sync.Once
	file_v1_service_auth_proto_rawDescData []byte
)

func file_v1_service_auth_proto_rawDescGZIP() []byte {
	file_v1_service_auth_proto_rawDescOnce.Do(func() {
		file_v1_service_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_service_auth_proto_rawDesc), len(file_v1_service_auth_proto_rawDesc)))
	})
	return file_v1_service_auth_proto_rawDescData
}

var file_v1_service_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_service_auth_proto_goTypes = []any{
	(*CheckUsernameRequest)(nil),  // 0: api.v1.service.CheckUsernameRequest
	(*CheckUsernameResponse)(nil), // 1: api.v1.service.CheckUsernameResponse
	(*InitAnonymousRequest)(nil),  // 2: api.v1.service.InitAnonymousRequest
	(*InitAnonymousResponse)(nil), // 3: api.v1.service.InitAnonymousResponse
	(*AuthenticateRequest)(nil),   // 4: api.v1.service.AuthenticateRequest
	(*AuthenticateResponse)(nil),  // 5: api.v1.service.AuthenticateResponse
	(*RefreshTokenRequest)(nil),   // 6: api.v1.service.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),  // 7: api.v1.service.RefreshTokenResponse
	(*entities.User)(nil),         // 8: api.v1.entities.User
}
var file_v1_service_auth_proto_depIdxs = []int32{
	8, // 0: api.v1.service.AuthenticateResponse.user:type_name -> api.v1.entities.User
	0, // 1: api.v1.service.AuthService.CheckUsername:input_type -> api.v1.service.CheckUsernameRequest
	2, // 2: api.v1.service.AuthService.InitAnonymous:input_type -> api.v1.service.InitAnonymousRequest
	4, // 3: api.v1.service.AuthService.Authenticate:input_type -> api.v1.service.AuthenticateRequest
	6, // 4: api.v1.service.AuthService.RefreshToken:input_type -> api.v1.service.RefreshTokenRequest
	1, // 5: api.v1.service.AuthService.CheckUsername:output_type -> api.v1.service.CheckUsernameResponse
	3, // 6: api.v1.service.AuthService.InitAnonymous:output_type -> api.v1.service.InitAnonymousResponse
	5, // 7: api.v1.service.AuthService.Authenticate:output_type -> api.v1.service.AuthenticateResponse
	7, // 8: api.v1.service.AuthService.RefreshToken:output_type -> api.v1.service.RefreshTokenResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_service_auth_proto_init() }
func file_v1_service_auth_proto_init() {
	if File_v1_service_auth_proto != nil {
		return
	}
	file_v1_service_auth_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_auth_proto_rawDesc), len(file_v1_service_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_auth_proto_goTypes,
		DependencyIndexes: file_v1_service_auth_proto_depIdxs,
		MessageInfos:      file_v1_service_auth_proto_msgTypes,
	}.Build()
	File_v1_service_auth_proto = out.File
	file_v1_service_auth_proto_goTypes = nil
	file_v1_service_auth_proto_depIdxs = nil
}
