// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/service/pin_service.proto

package servicev1

import (
	entities "github.com/radjathaher/alunalun/api/internal/protocgen/v1/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`   // Pin title/description
	Location      *entities.Location     `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"` // Geographic location
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePinRequest) Reset() {
	*x = CreatePinRequest{}
	mi := &file_v1_service_pin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePinRequest) ProtoMessage() {}

func (x *CreatePinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_pin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePinRequest.ProtoReflect.Descriptor instead.
func (*CreatePinRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_pin_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePinRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePinRequest) GetLocation() *entities.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type CreatePinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           *entities.Pin          `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePinResponse) Reset() {
	*x = CreatePinResponse{}
	mi := &file_v1_service_pin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePinResponse) ProtoMessage() {}

func (x *CreatePinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_pin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePinResponse.ProtoReflect.Descriptor instead.
func (*CreatePinResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_pin_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePinResponse) GetPin() *entities.Pin {
	if x != nil {
		return x.Pin
	}
	return nil
}

type ListPinsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bounding box coordinates
	North         float64 `protobuf:"fixed64,1,opt,name=north,proto3" json:"north,omitempty"`       // Max latitude
	South         float64 `protobuf:"fixed64,2,opt,name=south,proto3" json:"south,omitempty"`       // Min latitude
	East          float64 `protobuf:"fixed64,3,opt,name=east,proto3" json:"east,omitempty"`         // Max longitude
	West          float64 `protobuf:"fixed64,4,opt,name=west,proto3" json:"west,omitempty"`         // Min longitude
	Limit         *int32  `protobuf:"varint,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`  // Max results (default: 50)
	Cursor        *string `protobuf:"bytes,6,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"` // Pagination cursor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPinsRequest) Reset() {
	*x = ListPinsRequest{}
	mi := &file_v1_service_pin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPinsRequest) ProtoMessage() {}

func (x *ListPinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_pin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPinsRequest.ProtoReflect.Descriptor instead.
func (*ListPinsRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_pin_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListPinsRequest) GetNorth() float64 {
	if x != nil {
		return x.North
	}
	return 0
}

func (x *ListPinsRequest) GetSouth() float64 {
	if x != nil {
		return x.South
	}
	return 0
}

func (x *ListPinsRequest) GetEast() float64 {
	if x != nil {
		return x.East
	}
	return 0
}

func (x *ListPinsRequest) GetWest() float64 {
	if x != nil {
		return x.West
	}
	return 0
}

func (x *ListPinsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListPinsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListPinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pins          []*entities.Pin        `protobuf:"bytes,1,rep,name=pins,proto3" json:"pins,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"` // Cursor for next page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPinsResponse) Reset() {
	*x = ListPinsResponse{}
	mi := &file_v1_service_pin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPinsResponse) ProtoMessage() {}

func (x *ListPinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_pin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPinsResponse.ProtoReflect.Descriptor instead.
func (*ListPinsResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_pin_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListPinsResponse) GetPins() []*entities.Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

func (x *ListPinsResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

type GetPinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinId         string                 `protobuf:"bytes,1,opt,name=pin_id,json=pinId,proto3" json:"pin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPinRequest) Reset() {
	*x = GetPinRequest{}
	mi := &file_v1_service_pin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPinRequest) ProtoMessage() {}

func (x *GetPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_pin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPinRequest.ProtoReflect.Descriptor instead.
func (*GetPinRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_pin_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetPinRequest) GetPinId() string {
	if x != nil {
		return x.PinId
	}
	return ""
}

type GetPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           *entities.Pin          `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	Comments      []*entities.Comment    `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"` // All comments for this pin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPinResponse) Reset() {
	*x = GetPinResponse{}
	mi := &file_v1_service_pin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPinResponse) ProtoMessage() {}

func (x *GetPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_pin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPinResponse.ProtoReflect.Descriptor instead.
func (*GetPinResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_pin_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetPinResponse) GetPin() *entities.Pin {
	if x != nil {
		return x.Pin
	}
	return nil
}

func (x *GetPinResponse) GetComments() []*entities.Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinId         string                 `protobuf:"bytes,1,opt,name=pin_id,json=pinId,proto3" json:"pin_id,omitempty"`                // The pin to comment on
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                         // Comment text
	ParentId      *string                `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"` // Parent comment ID for replies
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_v1_service_pin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_pin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_pin_service_proto_rawDescGZIP(), []int{6}
}

func (x *AddCommentRequest) GetPinId() string {
	if x != nil {
		return x.PinId
	}
	return ""
}

func (x *AddCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddCommentRequest) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

type AddCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *entities.Comment      `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_v1_service_pin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_pin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_pin_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddCommentResponse) GetComment() *entities.Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

var File_v1_service_pin_service_proto protoreflect.FileDescriptor

const file_v1_service_pin_service_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/service/pin_service.proto\x12\x0eapi.v1.service\x1a\x15v1/entities/pin.proto\"c\n" +
	"\x10CreatePinRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x125\n" +
	"\blocation\x18\x02 \x01(\v2\x19.api.v1.entities.LocationR\blocation\";\n" +
	"\x11CreatePinResponse\x12&\n" +
	"\x03pin\x18\x01 \x01(\v2\x14.api.v1.entities.PinR\x03pin\"\xb2\x01\n" +
	"\x0fListPinsRequest\x12\x14\n" +
	"\x05north\x18\x01 \x01(\x01R\x05north\x12\x14\n" +
	"\x05south\x18\x02 \x01(\x01R\x05south\x12\x12\n" +
	"\x04east\x18\x03 \x01(\x01R\x04east\x12\x12\n" +
	"\x04west\x18\x04 \x01(\x01R\x04west\x12\x19\n" +
	"\x05limit\x18\x05 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\x06 \x01(\tH\x01R\x06cursor\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_cursor\"r\n" +
	"\x10ListPinsResponse\x12(\n" +
	"\x04pins\x18\x01 \x03(\v2\x14.api.v1.entities.PinR\x04pins\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"&\n" +
	"\rGetPinRequest\x12\x15\n" +
	"\x06pin_id\x18\x01 \x01(\tR\x05pinId\"n\n" +
	"\x0eGetPinResponse\x12&\n" +
	"\x03pin\x18\x01 \x01(\v2\x14.api.v1.entities.PinR\x03pin\x124\n" +
	"\bcomments\x18\x02 \x03(\v2\x18.api.v1.entities.CommentR\bcomments\"t\n" +
	"\x11AddCommentRequest\x12\x15\n" +
	"\x06pin_id\x18\x01 \x01(\tR\x05pinId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\tparent_id\x18\x03 \x01(\tH\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"H\n" +
	"\x12AddCommentResponse\x122\n" +
	"\acomment\x18\x01 \x01(\v2\x18.api.v1.entities.CommentR\acomment2\xcb\x02\n" +
	"\n" +
	"PinService\x12P\n" +
	"\tCreatePin\x12 .api.v1.service.CreatePinRequest\x1a!.api.v1.service.CreatePinResponse\x12M\n" +
	"\bListPins\x12\x1f.api.v1.service.ListPinsRequest\x1a .api.v1.service.ListPinsResponse\x12G\n" +
	"\x06GetPin\x12\x1d.api.v1.service.GetPinRequest\x1a\x1e.api.v1.service.GetPinResponse\x12S\n" +
	"\n" +
	"AddComment\x12!.api.v1.service.AddCommentRequest\x1a\".api.v1.service.AddCommentResponseBMZKgithub.com/radjathaher/alunalun/api/internal/protocgen/v1/service;servicev1b\x06proto3"

var (
	file_v1_service_pin_service_proto_rawDescOnce sync.Once
	file_v1_service_pin_service_proto_rawDescData []byte
)

func file_v1_service_pin_service_proto_rawDescGZIP() []byte {
	file_v1_service_pin_service_proto_rawDescOnce.Do(func() {
		file_v1_service_pin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_service_pin_service_proto_rawDesc), len(file_v1_service_pin_service_proto_rawDesc)))
	})
	return file_v1_service_pin_service_proto_rawDescData
}

var file_v1_service_pin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_service_pin_service_proto_goTypes = []any{
	(*CreatePinRequest)(nil),   // 0: api.v1.service.CreatePinRequest
	(*CreatePinResponse)(nil),  // 1: api.v1.service.CreatePinResponse
	(*ListPinsRequest)(nil),    // 2: api.v1.service.ListPinsRequest
	(*ListPinsResponse)(nil),   // 3: api.v1.service.ListPinsResponse
	(*GetPinRequest)(nil),      // 4: api.v1.service.GetPinRequest
	(*GetPinResponse)(nil),     // 5: api.v1.service.GetPinResponse
	(*AddCommentRequest)(nil),  // 6: api.v1.service.AddCommentRequest
	(*AddCommentResponse)(nil), // 7: api.v1.service.AddCommentResponse
	(*entities.Location)(nil),  // 8: api.v1.entities.Location
	(*entities.Pin)(nil),       // 9: api.v1.entities.Pin
	(*entities.Comment)(nil),   // 10: api.v1.entities.Comment
}
var file_v1_service_pin_service_proto_depIdxs = []int32{
	8,  // 0: api.v1.service.CreatePinRequest.location:type_name -> api.v1.entities.Location
	9,  // 1: api.v1.service.CreatePinResponse.pin:type_name -> api.v1.entities.Pin
	9,  // 2: api.v1.service.ListPinsResponse.pins:type_name -> api.v1.entities.Pin
	9,  // 3: api.v1.service.GetPinResponse.pin:type_name -> api.v1.entities.Pin
	10, // 4: api.v1.service.GetPinResponse.comments:type_name -> api.v1.entities.Comment
	10, // 5: api.v1.service.AddCommentResponse.comment:type_name -> api.v1.entities.Comment
	0,  // 6: api.v1.service.PinService.CreatePin:input_type -> api.v1.service.CreatePinRequest
	2,  // 7: api.v1.service.PinService.ListPins:input_type -> api.v1.service.ListPinsRequest
	4,  // 8: api.v1.service.PinService.GetPin:input_type -> api.v1.service.GetPinRequest
	6,  // 9: api.v1.service.PinService.AddComment:input_type -> api.v1.service.AddCommentRequest
	1,  // 10: api.v1.service.PinService.CreatePin:output_type -> api.v1.service.CreatePinResponse
	3,  // 11: api.v1.service.PinService.ListPins:output_type -> api.v1.service.ListPinsResponse
	5,  // 12: api.v1.service.PinService.GetPin:output_type -> api.v1.service.GetPinResponse
	7,  // 13: api.v1.service.PinService.AddComment:output_type -> api.v1.service.AddCommentResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_service_pin_service_proto_init() }
func file_v1_service_pin_service_proto_init() {
	if File_v1_service_pin_service_proto != nil {
		return
	}
	file_v1_service_pin_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_v1_service_pin_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_v1_service_pin_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_pin_service_proto_rawDesc), len(file_v1_service_pin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_pin_service_proto_goTypes,
		DependencyIndexes: file_v1_service_pin_service_proto_depIdxs,
		MessageInfos:      file_v1_service_pin_service_proto_msgTypes,
	}.Build()
	File_v1_service_pin_service_proto = out.File
	file_v1_service_pin_service_proto_goTypes = nil
	file_v1_service_pin_service_proto_depIdxs = nil
}
