// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/service/user.proto

package servicev1

import (
	entities "github.com/ckrwl/alunalun/api/gen/api/v1/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCurrentUserResponse returns current user
type GetCurrentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entities.User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserResponse) Reset() {
	*x = GetCurrentUserResponse{}
	mi := &file_v1_service_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserResponse) ProtoMessage() {}

func (x *GetCurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetCurrentUserResponse) GetUser() *entities.User {
	if x != nil {
		return x.User
	}
	return nil
}

// GetUserRequest by username
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_v1_service_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// GetUserResponse returns public profile
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *entities.UserProfile  `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_v1_service_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserResponse) GetProfile() *entities.UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// UpdateProfileRequest updates user profile
type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_v1_service_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

// UpdateProfileResponse returns updated user
type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entities.User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_v1_service_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProfileResponse) GetUser() *entities.User {
	if x != nil {
		return x.User
	}
	return nil
}

// GetAuthProvidersResponse returns linked providers
type GetAuthProvidersResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Providers     []*entities.AuthProvider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthProvidersResponse) Reset() {
	*x = GetAuthProvidersResponse{}
	mi := &file_v1_service_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthProvidersResponse) ProtoMessage() {}

func (x *GetAuthProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthProvidersResponse.ProtoReflect.Descriptor instead.
func (*GetAuthProvidersResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthProvidersResponse) GetProviders() []*entities.AuthProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// LinkAuthProviderRequest links new provider
type LinkAuthProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`     // "google", "github", etc
	Credential    string                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"` // OAuth token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkAuthProviderRequest) Reset() {
	*x = LinkAuthProviderRequest{}
	mi := &file_v1_service_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkAuthProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkAuthProviderRequest) ProtoMessage() {}

func (x *LinkAuthProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkAuthProviderRequest.ProtoReflect.Descriptor instead.
func (*LinkAuthProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{6}
}

func (x *LinkAuthProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LinkAuthProviderRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

// LinkAuthProviderResponse returns updated providers
type LinkAuthProviderResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Providers     []*entities.AuthProvider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkAuthProviderResponse) Reset() {
	*x = LinkAuthProviderResponse{}
	mi := &file_v1_service_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkAuthProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkAuthProviderResponse) ProtoMessage() {}

func (x *LinkAuthProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkAuthProviderResponse.ProtoReflect.Descriptor instead.
func (*LinkAuthProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{7}
}

func (x *LinkAuthProviderResponse) GetProviders() []*entities.AuthProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

// UnlinkAuthProviderRequest unlinks provider
type UnlinkAuthProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkAuthProviderRequest) Reset() {
	*x = UnlinkAuthProviderRequest{}
	mi := &file_v1_service_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkAuthProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkAuthProviderRequest) ProtoMessage() {}

func (x *UnlinkAuthProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkAuthProviderRequest.ProtoReflect.Descriptor instead.
func (*UnlinkAuthProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{8}
}

func (x *UnlinkAuthProviderRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

// UnlinkAuthProviderResponse returns remaining providers
type UnlinkAuthProviderResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Providers     []*entities.AuthProvider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkAuthProviderResponse) Reset() {
	*x = UnlinkAuthProviderResponse{}
	mi := &file_v1_service_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkAuthProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkAuthProviderResponse) ProtoMessage() {}

func (x *UnlinkAuthProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkAuthProviderResponse.ProtoReflect.Descriptor instead.
func (*UnlinkAuthProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_user_proto_rawDescGZIP(), []int{9}
}

func (x *UnlinkAuthProviderResponse) GetProviders() []*entities.AuthProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_v1_service_user_proto protoreflect.FileDescriptor

const file_v1_service_user_proto_rawDesc = "" +
	"\n" +
	"\x15v1/service/user.proto\x12\x0eapi.v1.service\x1a\x16v1/entities/user.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"C\n" +
	"\x16GetCurrentUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.api.v1.entities.UserR\x04user\",\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"I\n" +
	"\x0fGetUserResponse\x126\n" +
	"\aprofile\x18\x01 \x01(\v2\x1c.api.v1.entities.UserProfileR\aprofile\"\xbf\x01\n" +
	"\x14UpdateProfileRequest\x12;\n" +
	"\vupdate_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tH\x01R\tavatarUrl\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\r\n" +
	"\v_avatar_url\"B\n" +
	"\x15UpdateProfileResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.api.v1.entities.UserR\x04user\"W\n" +
	"\x18GetAuthProvidersResponse\x12;\n" +
	"\tproviders\x18\x01 \x03(\v2\x1d.api.v1.entities.AuthProviderR\tproviders\"U\n" +
	"\x17LinkAuthProviderRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\"W\n" +
	"\x18LinkAuthProviderResponse\x12;\n" +
	"\tproviders\x18\x01 \x03(\v2\x1d.api.v1.entities.AuthProviderR\tproviders\"7\n" +
	"\x19UnlinkAuthProviderRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"Y\n" +
	"\x1aUnlinkAuthProviderResponse\x12;\n" +
	"\tproviders\x18\x01 \x03(\v2\x1d.api.v1.entities.AuthProviderR\tproviders2\xb3\x04\n" +
	"\vUserService\x12P\n" +
	"\x0eGetCurrentUser\x12\x16.google.protobuf.Empty\x1a&.api.v1.service.GetCurrentUserResponse\x12J\n" +
	"\aGetUser\x12\x1e.api.v1.service.GetUserRequest\x1a\x1f.api.v1.service.GetUserResponse\x12\\\n" +
	"\rUpdateProfile\x12$.api.v1.service.UpdateProfileRequest\x1a%.api.v1.service.UpdateProfileResponse\x12T\n" +
	"\x10GetAuthProviders\x12\x16.google.protobuf.Empty\x1a(.api.v1.service.GetAuthProvidersResponse\x12e\n" +
	"\x10LinkAuthProvider\x12'.api.v1.service.LinkAuthProviderRequest\x1a(.api.v1.service.LinkAuthProviderResponse\x12k\n" +
	"\x12UnlinkAuthProvider\x12).api.v1.service.UnlinkAuthProviderRequest\x1a*.api.v1.service.UnlinkAuthProviderResponseB<Z:github.com/ckrwl/alunalun/api/gen/api/v1/service;servicev1b\x06proto3"

var (
	file_v1_service_user_proto_rawDescOnce sync.Once
	file_v1_service_user_proto_rawDescData []byte
)

func file_v1_service_user_proto_rawDescGZIP() []byte {
	file_v1_service_user_proto_rawDescOnce.Do(func() {
		file_v1_service_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_service_user_proto_rawDesc), len(file_v1_service_user_proto_rawDesc)))
	})
	return file_v1_service_user_proto_rawDescData
}

var file_v1_service_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_service_user_proto_goTypes = []any{
	(*GetCurrentUserResponse)(nil),     // 0: api.v1.service.GetCurrentUserResponse
	(*GetUserRequest)(nil),             // 1: api.v1.service.GetUserRequest
	(*GetUserResponse)(nil),            // 2: api.v1.service.GetUserResponse
	(*UpdateProfileRequest)(nil),       // 3: api.v1.service.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),      // 4: api.v1.service.UpdateProfileResponse
	(*GetAuthProvidersResponse)(nil),   // 5: api.v1.service.GetAuthProvidersResponse
	(*LinkAuthProviderRequest)(nil),    // 6: api.v1.service.LinkAuthProviderRequest
	(*LinkAuthProviderResponse)(nil),   // 7: api.v1.service.LinkAuthProviderResponse
	(*UnlinkAuthProviderRequest)(nil),  // 8: api.v1.service.UnlinkAuthProviderRequest
	(*UnlinkAuthProviderResponse)(nil), // 9: api.v1.service.UnlinkAuthProviderResponse
	(*entities.User)(nil),              // 10: api.v1.entities.User
	(*entities.UserProfile)(nil),       // 11: api.v1.entities.UserProfile
	(*fieldmaskpb.FieldMask)(nil),      // 12: google.protobuf.FieldMask
	(*entities.AuthProvider)(nil),      // 13: api.v1.entities.AuthProvider
	(*emptypb.Empty)(nil),              // 14: google.protobuf.Empty
}
var file_v1_service_user_proto_depIdxs = []int32{
	10, // 0: api.v1.service.GetCurrentUserResponse.user:type_name -> api.v1.entities.User
	11, // 1: api.v1.service.GetUserResponse.profile:type_name -> api.v1.entities.UserProfile
	12, // 2: api.v1.service.UpdateProfileRequest.update_mask:type_name -> google.protobuf.FieldMask
	10, // 3: api.v1.service.UpdateProfileResponse.user:type_name -> api.v1.entities.User
	13, // 4: api.v1.service.GetAuthProvidersResponse.providers:type_name -> api.v1.entities.AuthProvider
	13, // 5: api.v1.service.LinkAuthProviderResponse.providers:type_name -> api.v1.entities.AuthProvider
	13, // 6: api.v1.service.UnlinkAuthProviderResponse.providers:type_name -> api.v1.entities.AuthProvider
	14, // 7: api.v1.service.UserService.GetCurrentUser:input_type -> google.protobuf.Empty
	1,  // 8: api.v1.service.UserService.GetUser:input_type -> api.v1.service.GetUserRequest
	3,  // 9: api.v1.service.UserService.UpdateProfile:input_type -> api.v1.service.UpdateProfileRequest
	14, // 10: api.v1.service.UserService.GetAuthProviders:input_type -> google.protobuf.Empty
	6,  // 11: api.v1.service.UserService.LinkAuthProvider:input_type -> api.v1.service.LinkAuthProviderRequest
	8,  // 12: api.v1.service.UserService.UnlinkAuthProvider:input_type -> api.v1.service.UnlinkAuthProviderRequest
	0,  // 13: api.v1.service.UserService.GetCurrentUser:output_type -> api.v1.service.GetCurrentUserResponse
	2,  // 14: api.v1.service.UserService.GetUser:output_type -> api.v1.service.GetUserResponse
	4,  // 15: api.v1.service.UserService.UpdateProfile:output_type -> api.v1.service.UpdateProfileResponse
	5,  // 16: api.v1.service.UserService.GetAuthProviders:output_type -> api.v1.service.GetAuthProvidersResponse
	7,  // 17: api.v1.service.UserService.LinkAuthProvider:output_type -> api.v1.service.LinkAuthProviderResponse
	9,  // 18: api.v1.service.UserService.UnlinkAuthProvider:output_type -> api.v1.service.UnlinkAuthProviderResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_service_user_proto_init() }
func file_v1_service_user_proto_init() {
	if File_v1_service_user_proto != nil {
		return
	}
	file_v1_service_user_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_user_proto_rawDesc), len(file_v1_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_user_proto_goTypes,
		DependencyIndexes: file_v1_service_user_proto_depIdxs,
		MessageInfos:      file_v1_service_user_proto_msgTypes,
	}.Build()
	File_v1_service_user_proto = out.File
	file_v1_service_user_proto_goTypes = nil
	file_v1_service_user_proto_depIdxs = nil
}
