// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/service/user_service.proto

package servicev1

import (
	entities "github.com/radjathaher/alunalun/api/internal/protocgen/v1/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCurrentUserRequest - empty, uses session/JWT context
type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_v1_service_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_user_service_proto_rawDescGZIP(), []int{0}
}

type GetCurrentUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entities.User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // JWT for anonymous/registered user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserResponse) Reset() {
	*x = GetCurrentUserResponse{}
	mi := &file_v1_service_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserResponse) ProtoMessage() {}

func (x *GetCurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentUserResponse) GetUser() *entities.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetCurrentUserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // For password provider
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_v1_service_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entities.User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // New JWT with registered user claims
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_v1_service_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterUserResponse) GetUser() *entities.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterUserResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_v1_service_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_service_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *entities.User         `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_v1_service_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_service_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_service_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserResponse) GetUser() *entities.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_v1_service_user_service_proto protoreflect.FileDescriptor

const file_v1_service_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1dv1/service/user_service.proto\x12\x0eapi.v1.service\x1a\x16v1/entities/user.proto\"\x17\n" +
	"\x15GetCurrentUserRequest\"f\n" +
	"\x16GetCurrentUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.api.v1.entities.UserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"c\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"d\n" +
	"\x14RegisterUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.api.v1.entities.UserR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"<\n" +
	"\x0fGetUserResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.api.v1.entities.UserR\x04user2\x95\x02\n" +
	"\vUserService\x12_\n" +
	"\x0eGetCurrentUser\x12%.api.v1.service.GetCurrentUserRequest\x1a&.api.v1.service.GetCurrentUserResponse\x12Y\n" +
	"\fRegisterUser\x12#.api.v1.service.RegisterUserRequest\x1a$.api.v1.service.RegisterUserResponse\x12J\n" +
	"\aGetUser\x12\x1e.api.v1.service.GetUserRequest\x1a\x1f.api.v1.service.GetUserResponseBMZKgithub.com/radjathaher/alunalun/api/internal/protocgen/v1/service;servicev1b\x06proto3"

var (
	file_v1_service_user_service_proto_rawDescOnce sync.Once
	file_v1_service_user_service_proto_rawDescData []byte
)

func file_v1_service_user_service_proto_rawDescGZIP() []byte {
	file_v1_service_user_service_proto_rawDescOnce.Do(func() {
		file_v1_service_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_service_user_service_proto_rawDesc), len(file_v1_service_user_service_proto_rawDesc)))
	})
	return file_v1_service_user_service_proto_rawDescData
}

var file_v1_service_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_service_user_service_proto_goTypes = []any{
	(*GetCurrentUserRequest)(nil),  // 0: api.v1.service.GetCurrentUserRequest
	(*GetCurrentUserResponse)(nil), // 1: api.v1.service.GetCurrentUserResponse
	(*RegisterUserRequest)(nil),    // 2: api.v1.service.RegisterUserRequest
	(*RegisterUserResponse)(nil),   // 3: api.v1.service.RegisterUserResponse
	(*GetUserRequest)(nil),         // 4: api.v1.service.GetUserRequest
	(*GetUserResponse)(nil),        // 5: api.v1.service.GetUserResponse
	(*entities.User)(nil),          // 6: api.v1.entities.User
}
var file_v1_service_user_service_proto_depIdxs = []int32{
	6, // 0: api.v1.service.GetCurrentUserResponse.user:type_name -> api.v1.entities.User
	6, // 1: api.v1.service.RegisterUserResponse.user:type_name -> api.v1.entities.User
	6, // 2: api.v1.service.GetUserResponse.user:type_name -> api.v1.entities.User
	0, // 3: api.v1.service.UserService.GetCurrentUser:input_type -> api.v1.service.GetCurrentUserRequest
	2, // 4: api.v1.service.UserService.RegisterUser:input_type -> api.v1.service.RegisterUserRequest
	4, // 5: api.v1.service.UserService.GetUser:input_type -> api.v1.service.GetUserRequest
	1, // 6: api.v1.service.UserService.GetCurrentUser:output_type -> api.v1.service.GetCurrentUserResponse
	3, // 7: api.v1.service.UserService.RegisterUser:output_type -> api.v1.service.RegisterUserResponse
	5, // 8: api.v1.service.UserService.GetUser:output_type -> api.v1.service.GetUserResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_service_user_service_proto_init() }
func file_v1_service_user_service_proto_init() {
	if File_v1_service_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_service_user_service_proto_rawDesc), len(file_v1_service_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_service_user_service_proto_goTypes,
		DependencyIndexes: file_v1_service_user_service_proto_depIdxs,
		MessageInfos:      file_v1_service_user_service_proto_msgTypes,
	}.Build()
	File_v1_service_user_service_proto = out.File
	file_v1_service_user_service_proto_goTypes = nil
	file_v1_service_user_service_proto_depIdxs = nil
}
