// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID
	Email       string
	DisplayName *string
	AvatarUrl   *string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UserAuthProvider struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	EmailVerified  *bool
	IsPrimary      *bool
	CreatedAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
}

type UserEvent struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	SessionID     pgtype.UUID
	EventType     string
	IpAddress     *netip.Addr
	XForwardedFor *string
	XRealIp       *netip.Addr
	UserAgent     *string
	CreatedAt     pgtype.Timestamptz
	Metadata      []byte
}

type Username struct {
	Username  string
	UserID    pgtype.UUID
	SessionID pgtype.UUID
	ClaimedAt pgtype.Timestamptz
}
