// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Content   *string            `json:"content"`
	ParentID  *string            `json:"parent_id"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PostsLocation struct {
	PostID    string             `json:"post_id"`
	Location  interface{}        `json:"location"`
	Geohash   *string            `json:"geohash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        string             `json:"id"`
	Email     *string            `json:"email"`
	Username  string             `json:"username"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserEvent struct {
	ID          string             `json:"id"`
	UserID      *string            `json:"user_id"`
	SessionID   string             `json:"session_id"`
	EventType   string             `json:"event_type"`
	IpAddress   netip.Addr         `json:"ip_address"`
	Fingerprint *string            `json:"fingerprint"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
