// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Type       string             `json:"type"`
	ParentID   pgtype.UUID        `json:"parent_id"`
	Content    string             `json:"content"`
	Visibility *string            `json:"visibility"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PostsLocation struct {
	PostID      pgtype.UUID        `json:"post_id"`
	Coordinates interface{}        `json:"coordinates"`
	Geohash     string             `json:"geohash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	DisplayName *string            `json:"display_name"`
	AvatarUrl   *string            `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UserAuthProvider struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Provider         string             `json:"provider"`
	ProviderUserID   string             `json:"provider_user_id"`
	ProviderMetadata []byte             `json:"provider_metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
