// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByPost = `-- name: CountCommentsByPost :one
SELECT COUNT(*) FROM posts
WHERE parent_id = $1
`

func (q *Queries) CountCommentsByPost(ctx context.Context, parentID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByPost, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, user_id, type, content, parent_id, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, type, content, parent_id, metadata, created_at, updated_at
`

type CreatePostParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Type      string             `json:"type"`
	Content   *string            `json:"content"`
	ParentID  *string            `json:"parent_id"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg *CreatePostParams) (*Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Content,
		arg.ParentID,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Content,
		&i.ParentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, user_id, type, content, parent_id, metadata, created_at, updated_at FROM posts WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id string) (*Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Content,
		&i.ParentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPostWithAuthor = `-- name: GetPostWithAuthor :one
SELECT 
    p.id, p.user_id, p.type, p.content, p.parent_id, p.metadata, p.created_at, p.updated_at,
    u.id as author_id,
    u.username as author_username,
    u.email as author_email
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.id = $1
`

type GetPostWithAuthorRow struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Type           string             `json:"type"`
	Content        *string            `json:"content"`
	ParentID       *string            `json:"parent_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorID       string             `json:"author_id"`
	AuthorUsername string             `json:"author_username"`
	AuthorEmail    *string            `json:"author_email"`
}

func (q *Queries) GetPostWithAuthor(ctx context.Context, id string) (*GetPostWithAuthorRow, error) {
	row := q.db.QueryRow(ctx, getPostWithAuthor, id)
	var i GetPostWithAuthorRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Content,
		&i.ParentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.AuthorUsername,
		&i.AuthorEmail,
	)
	return &i, err
}

const listCommentsByPost = `-- name: ListCommentsByPost :many
SELECT 
    p.id, p.user_id, p.type, p.content, p.parent_id, p.metadata, p.created_at, p.updated_at,
    u.username as author_username
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.parent_id = $1
ORDER BY p.created_at ASC
`

type ListCommentsByPostRow struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Type           string             `json:"type"`
	Content        *string            `json:"content"`
	ParentID       *string            `json:"parent_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
}

func (q *Queries) ListCommentsByPost(ctx context.Context, parentID *string) ([]*ListCommentsByPostRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByPost, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListCommentsByPostRow{}
	for rows.Next() {
		var i ListCommentsByPostRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Content,
			&i.ParentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByType = `-- name: ListPostsByType :many
SELECT id, user_id, type, content, parent_id, metadata, created_at, updated_at FROM posts
WHERE type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByTypeParams struct {
	Type   string `json:"type"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPostsByType(ctx context.Context, arg *ListPostsByTypeParams) ([]*Post, error) {
	rows, err := q.db.Query(ctx, listPostsByType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Content,
			&i.ParentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUser = `-- name: ListPostsByUser :many
SELECT id, user_id, type, content, parent_id, metadata, created_at, updated_at FROM posts 
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPostsByUser(ctx context.Context, arg *ListPostsByUserParams) ([]*Post, error) {
	rows, err := q.db.Query(ctx, listPostsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Content,
			&i.ParentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPins = `-- name: ListRecentPins :many
SELECT 
    p.id, p.user_id, p.type, p.content, p.parent_id, p.metadata, p.created_at, p.updated_at,
    u.username as author_username,
    COALESCE(comment_counts.count, 0) as comment_count
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN (
    SELECT parent_id, COUNT(*) as count
    FROM posts
    WHERE parent_id IS NOT NULL
    GROUP BY parent_id
) comment_counts ON p.id = comment_counts.parent_id
WHERE p.type = 'pin'
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentPinsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRecentPinsRow struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Type           string             `json:"type"`
	Content        *string            `json:"content"`
	ParentID       *string            `json:"parent_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AuthorUsername string             `json:"author_username"`
	CommentCount   int64              `json:"comment_count"`
}

func (q *Queries) ListRecentPins(ctx context.Context, arg *ListRecentPinsParams) ([]*ListRecentPinsRow, error) {
	rows, err := q.db.Query(ctx, listRecentPins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListRecentPinsRow{}
	for rows.Next() {
		var i ListRecentPinsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Content,
			&i.ParentID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET 
    content = $2,
    metadata = $3,
    updated_at = $4
WHERE id = $1
RETURNING id, user_id, type, content, parent_id, metadata, created_at, updated_at
`

type UpdatePostParams struct {
	ID        string             `json:"id"`
	Content   *string            `json:"content"`
	Metadata  []byte             `json:"metadata"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg *UpdatePostParams) (*Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Content,
		arg.Metadata,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Content,
		&i.ParentID,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
