// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file v1/entities/user.proto (package api.v1.entities, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/entities/user.proto.
 */
export const file_v1_entities_user: GenFile = /*@__PURE__*/
  fileDesc("ChZ2MS9lbnRpdGllcy91c2VyLnByb3RvEg9hcGkudjEuZW50aXRpZXMiagoEVXNlchIKCgJpZBgBIAEoCRISCgVlbWFpbBgCIAEoCUgAiAEBEhAKCHVzZXJuYW1lGAMgASgJEhIKCmNyZWF0ZWRfYXQYBCABKAMSEgoKdXBkYXRlZF9hdBgFIAEoA0IICgZfZW1haWwikQEKEFVzZXJBdXRoUHJvdmlkZXISCgoCaWQYASABKAkSDwoHdXNlcl9pZBgCIAEoCRIQCghwcm92aWRlchgDIAEoCRIYChBwcm92aWRlcl91c2VyX2lkGAQgASgJEgwKBGRhdGEYBSABKAwSEgoKY3JlYXRlZF9hdBgGIAEoAxISCgp1cGRhdGVkX2F0GAcgASgDIu4BCgtVc2VyUHJvZmlsZRIPCgd1c2VyX2lkGAEgASgJEhcKCmZpcnN0X25hbWUYAiABKAlIAIgBARIWCglsYXN0X25hbWUYAyABKAlIAYgBARIXCgphdmF0YXJfdXJsGAQgASgJSAKIAQESEAoDYmlvGAUgASgJSAOIAQESFgoOZW1haWxfdmVyaWZpZWQYBiABKAgSEgoKY3JlYXRlZF9hdBgHIAEoAxISCgp1cGRhdGVkX2F0GAggASgDQg0KC19maXJzdF9uYW1lQgwKCl9sYXN0X25hbWVCDQoLX2F2YXRhcl91cmxCBgoEX2Jpbyp0CgpVc2VyU3RhdHVzEhsKF1VTRVJfU1RBVFVTX1VOU1BFQ0lGSUVEEAASFgoSVVNFUl9TVEFUVVNfQUNUSVZFEAESGAoUVVNFUl9TVEFUVVNfRElTQUJMRUQQAhIXChNVU0VSX1NUQVRVU19QRU5ESU5HEANCT1pNZ2l0aHViLmNvbS9yYWRqYXRoYWhlci9hbHVuYWx1bi9hcGkvaW50ZXJuYWwvcHJvdG9jZ2VuL3YxL2VudGl0aWVzO2VudGl0aWVzdjFiBnByb3RvMw");

/**
 * User represents a user in the system (matches database schema)
 *
 * @generated from message api.v1.entities.User
 */
export type User = Message<"api.v1.entities.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * NULL for anonymous users
   *
   * @generated from field: optional string email = 2;
   */
  email?: string;

  /**
   * "anon-X" for anonymous, "X" for registered
   *
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 created_at = 4;
   */
  createdAt: bigint;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 updated_at = 5;
   */
  updatedAt: bigint;
};

/**
 * Describes the message api.v1.entities.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_v1_entities_user, 0);

/**
 * UserAuthProvider represents an authentication provider for a user
 *
 * @generated from message api.v1.entities.UserAuthProvider
 */
export type UserAuthProvider = Message<"api.v1.entities.UserAuthProvider"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * 'password', 'google', 'apple', etc.
   *
   * @generated from field: string provider = 3;
   */
  provider: string;

  /**
   * User's ID at the provider
   *
   * @generated from field: string provider_user_id = 4;
   */
  providerUserId: string;

  /**
   * JSON provider-specific data
   *
   * @generated from field: bytes data = 5;
   */
  data: Uint8Array;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 created_at = 6;
   */
  createdAt: bigint;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 updated_at = 7;
   */
  updatedAt: bigint;
};

/**
 * Describes the message api.v1.entities.UserAuthProvider.
 * Use `create(UserAuthProviderSchema)` to create a new message.
 */
export const UserAuthProviderSchema: GenMessage<UserAuthProvider> = /*@__PURE__*/
  messageDesc(file_v1_entities_user, 1);

/**
 * UserProfile contains additional profile information for a user
 *
 * @generated from message api.v1.entities.UserProfile
 */
export type UserProfile = Message<"api.v1.entities.UserProfile"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: optional string first_name = 2;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 3;
   */
  lastName?: string;

  /**
   * @generated from field: optional string avatar_url = 4;
   */
  avatarUrl?: string;

  /**
   * @generated from field: optional string bio = 5;
   */
  bio?: string;

  /**
   * @generated from field: bool email_verified = 6;
   */
  emailVerified: boolean;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 created_at = 7;
   */
  createdAt: bigint;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 updated_at = 8;
   */
  updatedAt: bigint;
};

/**
 * Describes the message api.v1.entities.UserProfile.
 * Use `create(UserProfileSchema)` to create a new message.
 */
export const UserProfileSchema: GenMessage<UserProfile> = /*@__PURE__*/
  messageDesc(file_v1_entities_user, 2);

/**
 * UserStatus represents the status of a user
 *
 * @generated from enum api.v1.entities.UserStatus
 */
export enum UserStatus {
  /**
   * @generated from enum value: USER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: USER_STATUS_DISABLED = 2;
   */
  DISABLED = 2,

  /**
   * @generated from enum value: USER_STATUS_PENDING = 3;
   */
  PENDING = 3,
}

/**
 * Describes the enum api.v1.entities.UserStatus.
 */
export const UserStatusSchema: GenEnum<UserStatus> = /*@__PURE__*/
  enumDesc(file_v1_entities_user, 0);

