// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file v1/entities/user.proto (package api.v1.entities, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/entities/user.proto.
 */
export const file_v1_entities_user: GenFile = /*@__PURE__*/
  fileDesc("ChZ2MS9lbnRpdGllcy91c2VyLnByb3RvEg9hcGkudjEuZW50aXRpZXMi0gEKBFVzZXISCgoCaWQYASABKAkSEgoFZW1haWwYAiABKAlIAIgBARIQCgh1c2VybmFtZRgDIAEoCRI1CghtZXRhZGF0YRgEIAMoCzIjLmFwaS52MS5lbnRpdGllcy5Vc2VyLk1ldGFkYXRhRW50cnkSEgoKY3JlYXRlZF9hdBgFIAEoAxISCgp1cGRhdGVkX2F0GAYgASgDGi8KDU1ldGFkYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUIICgZfZW1haWwqdAoKVXNlclN0YXR1cxIbChdVU0VSX1NUQVRVU19VTlNQRUNJRklFRBAAEhYKElVTRVJfU1RBVFVTX0FDVElWRRABEhgKFFVTRVJfU1RBVFVTX0RJU0FCTEVEEAISFwoTVVNFUl9TVEFUVVNfUEVORElORxADQk9aTWdpdGh1Yi5jb20vcmFkamF0aGFoZXIvYWx1bmFsdW4vYXBpL2ludGVybmFsL3Byb3RvY2dlbi92MS9lbnRpdGllcztlbnRpdGllc3YxYgZwcm90bzM");

/**
 * User represents a user in the system (matches database schema)
 *
 * @generated from message api.v1.entities.User
 */
export type User = Message<"api.v1.entities.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * NULL for anonymous users
   *
   * @generated from field: optional string email = 2;
   */
  email?: string;

  /**
   * "anon-xyz" for anonymous, regular for registered
   *
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * Flexible key-value metadata
   *
   * @generated from field: map<string, string> metadata = 4;
   */
  metadata: { [key: string]: string };

  /**
   * Unix timestamp
   *
   * @generated from field: int64 created_at = 5;
   */
  createdAt: bigint;

  /**
   * Unix timestamp
   *
   * @generated from field: int64 updated_at = 6;
   */
  updatedAt: bigint;
};

/**
 * Describes the message api.v1.entities.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_v1_entities_user, 0);

/**
 * UserStatus represents the status of a user
 *
 * @generated from enum api.v1.entities.UserStatus
 */
export enum UserStatus {
  /**
   * @generated from enum value: USER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: USER_STATUS_DISABLED = 2;
   */
  DISABLED = 2,

  /**
   * @generated from enum value: USER_STATUS_PENDING = 3;
   */
  PENDING = 3,
}

/**
 * Describes the enum api.v1.entities.UserStatus.
 */
export const UserStatusSchema: GenEnum<UserStatus> = /*@__PURE__*/
  enumDesc(file_v1_entities_user, 0);

