// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/service/auth.proto (package api.v1.service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "../entities/user_pb";
import { file_v1_entities_user } from "../entities/user_pb";
import { file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/service/auth.proto.
 */
export const file_v1_service_auth: GenFile = /*@__PURE__*/
  fileDesc("ChV2MS9zZXJ2aWNlL2F1dGgucHJvdG8SDmFwaS52MS5zZXJ2aWNlIigKFENoZWNrVXNlcm5hbWVSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJIjsKFUNoZWNrVXNlcm5hbWVSZXNwb25zZRIRCglhdmFpbGFibGUYASABKAgSDwoHbWVzc2FnZRgCIAEoCSIoChRJbml0QW5vbnltb3VzUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCSJMChVJbml0QW5vbnltb3VzUmVzcG9uc2USDQoFdG9rZW4YASABKAkSEgoKc2Vzc2lvbl9pZBgCIAEoCRIQCgh1c2VybmFtZRgDIAEoCSJjChNBdXRoZW50aWNhdGVSZXF1ZXN0EhAKCHByb3ZpZGVyGAEgASgJEhIKCmNyZWRlbnRpYWwYAiABKAkSFwoKc2Vzc2lvbl9pZBgDIAEoCUgAiAEBQg0KC19zZXNzaW9uX2lkImQKFEF1dGhlbnRpY2F0ZVJlc3BvbnNlEg0KBXRva2VuGAEgASgJEiMKBHVzZXIYAiABKAsyFS5hcGkudjEuZW50aXRpZXMuVXNlchIYChBzZXNzaW9uX21pZ3JhdGVkGAMgASgIIiwKE1JlZnJlc2hUb2tlblJlcXVlc3QSFQoNZXhwaXJlZF90b2tlbhgBIAEoCSIlChRSZWZyZXNoVG9rZW5SZXNwb25zZRINCgV0b2tlbhgBIAEoCTL/AgoLQXV0aFNlcnZpY2USXAoNQ2hlY2tVc2VybmFtZRIkLmFwaS52MS5zZXJ2aWNlLkNoZWNrVXNlcm5hbWVSZXF1ZXN0GiUuYXBpLnYxLnNlcnZpY2UuQ2hlY2tVc2VybmFtZVJlc3BvbnNlElwKDUluaXRBbm9ueW1vdXMSJC5hcGkudjEuc2VydmljZS5Jbml0QW5vbnltb3VzUmVxdWVzdBolLmFwaS52MS5zZXJ2aWNlLkluaXRBbm9ueW1vdXNSZXNwb25zZRJZCgxBdXRoZW50aWNhdGUSIy5hcGkudjEuc2VydmljZS5BdXRoZW50aWNhdGVSZXF1ZXN0GiQuYXBpLnYxLnNlcnZpY2UuQXV0aGVudGljYXRlUmVzcG9uc2USWQoMUmVmcmVzaFRva2VuEiMuYXBpLnYxLnNlcnZpY2UuUmVmcmVzaFRva2VuUmVxdWVzdBokLmFwaS52MS5zZXJ2aWNlLlJlZnJlc2hUb2tlblJlc3BvbnNlQjxaOmdpdGh1Yi5jb20vY2tyd2wvYWx1bmFsdW4vYXBpL2dlbi9hcGkvdjEvc2VydmljZTtzZXJ2aWNldjFiBnByb3RvMw", [file_v1_entities_user, file_google_protobuf_field_mask]);

/**
 * CheckUsernameRequest checks availability
 *
 * @generated from message api.v1.service.CheckUsernameRequest
 */
export type CheckUsernameRequest = Message<"api.v1.service.CheckUsernameRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message api.v1.service.CheckUsernameRequest.
 * Use `create(CheckUsernameRequestSchema)` to create a new message.
 */
export const CheckUsernameRequestSchema: GenMessage<CheckUsernameRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_auth, 0);

/**
 * CheckUsernameResponse returns availability
 *
 * @generated from message api.v1.service.CheckUsernameResponse
 */
export type CheckUsernameResponse = Message<"api.v1.service.CheckUsernameResponse"> & {
  /**
   * @generated from field: bool available = 1;
   */
  available: boolean;

  /**
   * Optional reason if not available
   *
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message api.v1.service.CheckUsernameResponse.
 * Use `create(CheckUsernameResponseSchema)` to create a new message.
 */
export const CheckUsernameResponseSchema: GenMessage<CheckUsernameResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_auth, 1);

/**
 * InitAnonymousRequest creates anonymous session
 *
 * @generated from message api.v1.service.InitAnonymousRequest
 */
export type InitAnonymousRequest = Message<"api.v1.service.InitAnonymousRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message api.v1.service.InitAnonymousRequest.
 * Use `create(InitAnonymousRequestSchema)` to create a new message.
 */
export const InitAnonymousRequestSchema: GenMessage<InitAnonymousRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_auth, 2);

/**
 * InitAnonymousResponse returns anonymous token
 *
 * @generated from message api.v1.service.InitAnonymousResponse
 */
export type InitAnonymousResponse = Message<"api.v1.service.InitAnonymousResponse"> & {
  /**
   * JWT with no expiration
   *
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * Server-generated UUID
   *
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * Confirmed username
   *
   * @generated from field: string username = 3;
   */
  username: string;
};

/**
 * Describes the message api.v1.service.InitAnonymousResponse.
 * Use `create(InitAnonymousResponseSchema)` to create a new message.
 */
export const InitAnonymousResponseSchema: GenMessage<InitAnonymousResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_auth, 3);

/**
 * AuthenticateRequest for provider-based auth
 *
 * @generated from message api.v1.service.AuthenticateRequest
 */
export type AuthenticateRequest = Message<"api.v1.service.AuthenticateRequest"> & {
  /**
   * "google", "magic_link", etc
   *
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * ID token, magic token, etc
   *
   * @generated from field: string credential = 2;
   */
  credential: string;

  /**
   * For migration from anonymous
   *
   * @generated from field: optional string session_id = 3;
   */
  sessionId?: string;
};

/**
 * Describes the message api.v1.service.AuthenticateRequest.
 * Use `create(AuthenticateRequestSchema)` to create a new message.
 */
export const AuthenticateRequestSchema: GenMessage<AuthenticateRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_auth, 4);

/**
 * AuthenticateResponse returns auth token
 *
 * @generated from message api.v1.service.AuthenticateResponse
 */
export type AuthenticateResponse = Message<"api.v1.service.AuthenticateResponse"> & {
  /**
   * JWT with 1hr expiration
   *
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: api.v1.entities.User user = 2;
   */
  user?: User;

  /**
   * If session_id was provided and migrated
   *
   * @generated from field: bool session_migrated = 3;
   */
  sessionMigrated: boolean;
};

/**
 * Describes the message api.v1.service.AuthenticateResponse.
 * Use `create(AuthenticateResponseSchema)` to create a new message.
 */
export const AuthenticateResponseSchema: GenMessage<AuthenticateResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_auth, 5);

/**
 * RefreshTokenRequest refreshes expired JWT
 *
 * @generated from message api.v1.service.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"api.v1.service.RefreshTokenRequest"> & {
  /**
   * The expired JWT to refresh
   *
   * @generated from field: string expired_token = 1;
   */
  expiredToken: string;
};

/**
 * Describes the message api.v1.service.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_auth, 6);

/**
 * RefreshTokenResponse returns new token
 *
 * @generated from message api.v1.service.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"api.v1.service.RefreshTokenResponse"> & {
  /**
   * New JWT with 1hr expiration
   *
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message api.v1.service.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_auth, 7);

/**
 * AuthService handles authentication flows
 *
 * @generated from service api.v1.service.AuthService
 */
export const AuthService: GenService<{
  /**
   * Check if username is available
   *
   * @generated from rpc api.v1.service.AuthService.CheckUsername
   */
  checkUsername: {
    methodKind: "unary";
    input: typeof CheckUsernameRequestSchema;
    output: typeof CheckUsernameResponseSchema;
  },
  /**
   * Initialize anonymous session (generates session_id + token)
   *
   * @generated from rpc api.v1.service.AuthService.InitAnonymous
   */
  initAnonymous: {
    methodKind: "unary";
    input: typeof InitAnonymousRequestSchema;
    output: typeof InitAnonymousResponseSchema;
  },
  /**
   * Authenticate with provider (Google, magic link, etc)
   *
   * @generated from rpc api.v1.service.AuthService.Authenticate
   */
  authenticate: {
    methodKind: "unary";
    input: typeof AuthenticateRequestSchema;
    output: typeof AuthenticateResponseSchema;
  },
  /**
   * Refresh authenticated tokens (anonymous tokens never expire)
   *
   * @generated from rpc api.v1.service.AuthService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_service_auth, 0);

