// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/common/pagination.proto (package api.v1.common, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file v1/common/pagination.proto.
 */
export const file_v1_common_pagination: GenFile =
  /*@__PURE__*/
  fileDesc(
    "Chp2MS9jb21tb24vcGFnaW5hdGlvbi5wcm90bxINYXBpLnYxLmNvbW1vbiI8CgtQYWdlUmVxdWVzdBINCgVsaW1pdBgBIAEoBRIOCgZvZmZzZXQYAiABKAUSDgoGY3Vyc29yGAMgASgJImMKDFBhZ2VSZXNwb25zZRINCgV0b3RhbBgBIAEoBRINCgVsaW1pdBgCIAEoBRIOCgZvZmZzZXQYAyABKAUSEAoIaGFzX21vcmUYBCABKAgSEwoLbmV4dF9jdXJzb3IYBSABKAlCOlo4Z2l0aHViLmNvbS9ja3J3bC9hbHVuYWx1bi9hcGkvZ2VuL2FwaS92MS9jb21tb247Y29tbW9udjFiBnByb3RvMw",
  );

/**
 * PageRequest for paginated queries
 *
 * @generated from message api.v1.common.PageRequest
 */
export type PageRequest = Message<"api.v1.common.PageRequest"> & {
  /**
   * Max items per page
   *
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * Number of items to skip
   *
   * @generated from field: int32 offset = 2;
   */
  offset: number;

  /**
   * Alternative cursor-based pagination
   *
   * @generated from field: string cursor = 3;
   */
  cursor: string;
};

/**
 * Describes the message api.v1.common.PageRequest.
 * Use `create(PageRequestSchema)` to create a new message.
 */
export const PageRequestSchema: GenMessage<PageRequest> =
  /*@__PURE__*/
  messageDesc(file_v1_common_pagination, 0);

/**
 * PageResponse with pagination metadata
 *
 * @generated from message api.v1.common.PageResponse
 */
export type PageResponse = Message<"api.v1.common.PageResponse"> & {
  /**
   * Total number of items
   *
   * @generated from field: int32 total = 1;
   */
  total: number;

  /**
   * Items per page
   *
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * Current offset
   *
   * @generated from field: int32 offset = 3;
   */
  offset: number;

  /**
   * Whether more pages exist
   *
   * @generated from field: bool has_more = 4;
   */
  hasMore: boolean;

  /**
   * Cursor for next page
   *
   * @generated from field: string next_cursor = 5;
   */
  nextCursor: string;
};

/**
 * Describes the message api.v1.common.PageResponse.
 * Use `create(PageResponseSchema)` to create a new message.
 */
export const PageResponseSchema: GenMessage<PageResponse> =
  /*@__PURE__*/
  messageDesc(file_v1_common_pagination, 1);
