// @generated by protoc-gen-connect-query v2.1.1 with parameter "target=ts"
// @generated from file v1/service/auth.proto (package api.v1.service.auth, syntax proto3)
/* eslint-disable */

import { AuthService } from "./auth_pb";

/**
 * Check if username is available
 *
 * @generated from rpc api.v1.service.auth.AuthService.CheckUsername
 */
export const checkUsername = AuthService.method.checkUsername;

/**
 * Initialize anonymous session (generates session_id + token)
 *
 * @generated from rpc api.v1.service.auth.AuthService.InitAnonymous
 */
export const initAnonymous = AuthService.method.initAnonymous;

/**
 * Authenticate with provider (Google, magic link, etc)
 *
 * @generated from rpc api.v1.service.auth.AuthService.Authenticate
 */
export const authenticate = AuthService.method.authenticate;

/**
 * Refresh authenticated tokens (anonymous tokens never expire)
 *
 * @generated from rpc api.v1.service.auth.AuthService.RefreshToken
 */
export const refreshToken = AuthService.method.refreshToken;
