// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file v1/service/pin_service.proto (package api.v1.service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Comment, Location, Pin } from "../entities/pin_pb";
import { file_v1_entities_pin } from "../entities/pin_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/service/pin_service.proto.
 */
export const file_v1_service_pin_service: GenFile = /*@__PURE__*/
  fileDesc("Chx2MS9zZXJ2aWNlL3Bpbl9zZXJ2aWNlLnByb3RvEg5hcGkudjEuc2VydmljZSJQChBDcmVhdGVQaW5SZXF1ZXN0Eg8KB2NvbnRlbnQYASABKAkSKwoIbG9jYXRpb24YAiABKAsyGS5hcGkudjEuZW50aXRpZXMuTG9jYXRpb24iNgoRQ3JlYXRlUGluUmVzcG9uc2USIQoDcGluGAEgASgLMhQuYXBpLnYxLmVudGl0aWVzLlBpbiKCAQoPTGlzdFBpbnNSZXF1ZXN0EhAKCGxhdGl0dWRlGAEgASgBEhEKCWxvbmdpdHVkZRgCIAEoARIMCgR6b29tGAMgASgFEhIKBWxpbWl0GAQgASgFSACIAQESEwoGY3Vyc29yGAUgASgJSAGIAQFCCAoGX2xpbWl0QgkKB19jdXJzb3IiYAoQTGlzdFBpbnNSZXNwb25zZRIiCgRwaW5zGAEgAygLMhQuYXBpLnYxLmVudGl0aWVzLlBpbhIYCgtuZXh0X2N1cnNvchgCIAEoCUgAiAEBQg4KDF9uZXh0X2N1cnNvciIfCg1HZXRQaW5SZXF1ZXN0Eg4KBnBpbl9pZBgBIAEoCSJfCg5HZXRQaW5SZXNwb25zZRIhCgNwaW4YASABKAsyFC5hcGkudjEuZW50aXRpZXMuUGluEioKCGNvbW1lbnRzGAIgAygLMhguYXBpLnYxLmVudGl0aWVzLkNvbW1lbnQiWgoRQWRkQ29tbWVudFJlcXVlc3QSDgoGcGluX2lkGAEgASgJEg8KB2NvbnRlbnQYAiABKAkSFgoJcGFyZW50X2lkGAMgASgJSACIAQFCDAoKX3BhcmVudF9pZCI/ChJBZGRDb21tZW50UmVzcG9uc2USKQoHY29tbWVudBgBIAEoCzIYLmFwaS52MS5lbnRpdGllcy5Db21tZW50IiIKEERlbGV0ZVBpblJlcXVlc3QSDgoGcGluX2lkGAEgASgJIiQKEURlbGV0ZVBpblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgynQMKClBpblNlcnZpY2USUAoJQ3JlYXRlUGluEiAuYXBpLnYxLnNlcnZpY2UuQ3JlYXRlUGluUmVxdWVzdBohLmFwaS52MS5zZXJ2aWNlLkNyZWF0ZVBpblJlc3BvbnNlEk0KCExpc3RQaW5zEh8uYXBpLnYxLnNlcnZpY2UuTGlzdFBpbnNSZXF1ZXN0GiAuYXBpLnYxLnNlcnZpY2UuTGlzdFBpbnNSZXNwb25zZRJHCgZHZXRQaW4SHS5hcGkudjEuc2VydmljZS5HZXRQaW5SZXF1ZXN0Gh4uYXBpLnYxLnNlcnZpY2UuR2V0UGluUmVzcG9uc2USUwoKQWRkQ29tbWVudBIhLmFwaS52MS5zZXJ2aWNlLkFkZENvbW1lbnRSZXF1ZXN0GiIuYXBpLnYxLnNlcnZpY2UuQWRkQ29tbWVudFJlc3BvbnNlElAKCURlbGV0ZVBpbhIgLmFwaS52MS5zZXJ2aWNlLkRlbGV0ZVBpblJlcXVlc3QaIS5hcGkudjEuc2VydmljZS5EZWxldGVQaW5SZXNwb25zZUJNWktnaXRodWIuY29tL3JhZGphdGhhaGVyL2FsdW5hbHVuL2FwaS9pbnRlcm5hbC9wcm90b2NnZW4vdjEvc2VydmljZTtzZXJ2aWNldjFiBnByb3RvMw", [file_v1_entities_pin]);

/**
 * @generated from message api.v1.service.CreatePinRequest
 */
export type CreatePinRequest = Message<"api.v1.service.CreatePinRequest"> & {
  /**
   * Pin title/description
   *
   * @generated from field: string content = 1;
   */
  content: string;

  /**
   * Geographic location
   *
   * @generated from field: api.v1.entities.Location location = 2;
   */
  location?: Location;
};

/**
 * Describes the message api.v1.service.CreatePinRequest.
 * Use `create(CreatePinRequestSchema)` to create a new message.
 */
export const CreatePinRequestSchema: GenMessage<CreatePinRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 0);

/**
 * @generated from message api.v1.service.CreatePinResponse
 */
export type CreatePinResponse = Message<"api.v1.service.CreatePinResponse"> & {
  /**
   * @generated from field: api.v1.entities.Pin pin = 1;
   */
  pin?: Pin;
};

/**
 * Describes the message api.v1.service.CreatePinResponse.
 * Use `create(CreatePinResponseSchema)` to create a new message.
 */
export const CreatePinResponseSchema: GenMessage<CreatePinResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 1);

/**
 * @generated from message api.v1.service.ListPinsRequest
 */
export type ListPinsRequest = Message<"api.v1.service.ListPinsRequest"> & {
  /**
   * Center point coordinates
   *
   * Center latitude
   *
   * @generated from field: double latitude = 1;
   */
  latitude: number;

  /**
   * Center longitude
   *
   * @generated from field: double longitude = 2;
   */
  longitude: number;

  /**
   * Zoom level (determines precision and limit)
   *
   * @generated from field: int32 zoom = 3;
   */
  zoom: number;

  /**
   * Override default limit
   *
   * @generated from field: optional int32 limit = 4;
   */
  limit?: number;

  /**
   * Pagination cursor
   *
   * @generated from field: optional string cursor = 5;
   */
  cursor?: string;
};

/**
 * Describes the message api.v1.service.ListPinsRequest.
 * Use `create(ListPinsRequestSchema)` to create a new message.
 */
export const ListPinsRequestSchema: GenMessage<ListPinsRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 2);

/**
 * @generated from message api.v1.service.ListPinsResponse
 */
export type ListPinsResponse = Message<"api.v1.service.ListPinsResponse"> & {
  /**
   * @generated from field: repeated api.v1.entities.Pin pins = 1;
   */
  pins: Pin[];

  /**
   * Cursor for next page
   *
   * @generated from field: optional string next_cursor = 2;
   */
  nextCursor?: string;
};

/**
 * Describes the message api.v1.service.ListPinsResponse.
 * Use `create(ListPinsResponseSchema)` to create a new message.
 */
export const ListPinsResponseSchema: GenMessage<ListPinsResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 3);

/**
 * @generated from message api.v1.service.GetPinRequest
 */
export type GetPinRequest = Message<"api.v1.service.GetPinRequest"> & {
  /**
   * @generated from field: string pin_id = 1;
   */
  pinId: string;
};

/**
 * Describes the message api.v1.service.GetPinRequest.
 * Use `create(GetPinRequestSchema)` to create a new message.
 */
export const GetPinRequestSchema: GenMessage<GetPinRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 4);

/**
 * @generated from message api.v1.service.GetPinResponse
 */
export type GetPinResponse = Message<"api.v1.service.GetPinResponse"> & {
  /**
   * @generated from field: api.v1.entities.Pin pin = 1;
   */
  pin?: Pin;

  /**
   * All comments for this pin
   *
   * @generated from field: repeated api.v1.entities.Comment comments = 2;
   */
  comments: Comment[];
};

/**
 * Describes the message api.v1.service.GetPinResponse.
 * Use `create(GetPinResponseSchema)` to create a new message.
 */
export const GetPinResponseSchema: GenMessage<GetPinResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 5);

/**
 * @generated from message api.v1.service.AddCommentRequest
 */
export type AddCommentRequest = Message<"api.v1.service.AddCommentRequest"> & {
  /**
   * The pin to comment on
   *
   * @generated from field: string pin_id = 1;
   */
  pinId: string;

  /**
   * Comment text
   *
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * Parent comment ID for replies
   *
   * @generated from field: optional string parent_id = 3;
   */
  parentId?: string;
};

/**
 * Describes the message api.v1.service.AddCommentRequest.
 * Use `create(AddCommentRequestSchema)` to create a new message.
 */
export const AddCommentRequestSchema: GenMessage<AddCommentRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 6);

/**
 * @generated from message api.v1.service.AddCommentResponse
 */
export type AddCommentResponse = Message<"api.v1.service.AddCommentResponse"> & {
  /**
   * @generated from field: api.v1.entities.Comment comment = 1;
   */
  comment?: Comment;
};

/**
 * Describes the message api.v1.service.AddCommentResponse.
 * Use `create(AddCommentResponseSchema)` to create a new message.
 */
export const AddCommentResponseSchema: GenMessage<AddCommentResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 7);

/**
 * @generated from message api.v1.service.DeletePinRequest
 */
export type DeletePinRequest = Message<"api.v1.service.DeletePinRequest"> & {
  /**
   * @generated from field: string pin_id = 1;
   */
  pinId: string;
};

/**
 * Describes the message api.v1.service.DeletePinRequest.
 * Use `create(DeletePinRequestSchema)` to create a new message.
 */
export const DeletePinRequestSchema: GenMessage<DeletePinRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 8);

/**
 * @generated from message api.v1.service.DeletePinResponse
 */
export type DeletePinResponse = Message<"api.v1.service.DeletePinResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message api.v1.service.DeletePinResponse.
 * Use `create(DeletePinResponseSchema)` to create a new message.
 */
export const DeletePinResponseSchema: GenMessage<DeletePinResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_pin_service, 9);

/**
 * PinService handles pin and comment operations
 *
 * @generated from service api.v1.service.PinService
 */
export const PinService: GenService<{
  /**
   * Create a new pin on the map
   *
   * @generated from rpc api.v1.service.PinService.CreatePin
   */
  createPin: {
    methodKind: "unary";
    input: typeof CreatePinRequestSchema;
    output: typeof CreatePinResponseSchema;
  },
  /**
   * Get pins within a geographic area
   *
   * @generated from rpc api.v1.service.PinService.ListPins
   */
  listPins: {
    methodKind: "unary";
    input: typeof ListPinsRequestSchema;
    output: typeof ListPinsResponseSchema;
  },
  /**
   * Get a single pin with its comments
   *
   * @generated from rpc api.v1.service.PinService.GetPin
   */
  getPin: {
    methodKind: "unary";
    input: typeof GetPinRequestSchema;
    output: typeof GetPinResponseSchema;
  },
  /**
   * Add a comment to a pin
   *
   * @generated from rpc api.v1.service.PinService.AddComment
   */
  addComment: {
    methodKind: "unary";
    input: typeof AddCommentRequestSchema;
    output: typeof AddCommentResponseSchema;
  },
  /**
   * Delete a pin (owner only)
   *
   * @generated from rpc api.v1.service.PinService.DeletePin
   */
  deletePin: {
    methodKind: "unary";
    input: typeof DeletePinRequestSchema;
    output: typeof DeletePinResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_service_pin_service, 0);

