// @generated by protoc-gen-connect-query v2.1.1 with parameter "target=ts"
// @generated from file v1/service/pin_service.proto (package api.v1.service, syntax proto3)
/* eslint-disable */

import { PinService } from "./pin_service_pb";

/**
 * Create a new pin on the map
 *
 * @generated from rpc api.v1.service.PinService.CreatePin
 */
export const createPin = PinService.method.createPin;

/**
 * Get pins within a geographic area
 *
 * @generated from rpc api.v1.service.PinService.ListPins
 */
export const listPins = PinService.method.listPins;

/**
 * Get a single pin with its comments
 *
 * @generated from rpc api.v1.service.PinService.GetPin
 */
export const getPin = PinService.method.getPin;

/**
 * Add a comment to a pin
 *
 * @generated from rpc api.v1.service.PinService.AddComment
 */
export const addComment = PinService.method.addComment;
