// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file v1/service/user.proto (package api.v1.service, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import {
  GetAuthProvidersResponse,
  GetCurrentUserResponse,
  GetUserRequest,
  GetUserResponse,
  LinkAuthProviderRequest,
  LinkAuthProviderResponse,
  UnlinkAuthProviderRequest,
  UnlinkAuthProviderResponse,
  UpdateProfileRequest,
  UpdateProfileResponse,
} from "./user_pb.js";

/**
 * UserService handles user profile management
 *
 * @generated from service api.v1.service.UserService
 */
export const UserService = {
  typeName: "api.v1.service.UserService",
  methods: {
    /**
     * Get current user profile
     *
     * @generated from rpc api.v1.service.UserService.GetCurrentUser
     */
    getCurrentUser: {
      name: "GetCurrentUser",
      I: Empty,
      O: GetCurrentUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get user by username
     *
     * @generated from rpc api.v1.service.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update current user profile
     *
     * @generated from rpc api.v1.service.UserService.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: UpdateProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get linked auth providers
     *
     * @generated from rpc api.v1.service.UserService.GetAuthProviders
     */
    getAuthProviders: {
      name: "GetAuthProviders",
      I: Empty,
      O: GetAuthProvidersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Link new auth provider
     *
     * @generated from rpc api.v1.service.UserService.LinkAuthProvider
     */
    linkAuthProvider: {
      name: "LinkAuthProvider",
      I: LinkAuthProviderRequest,
      O: LinkAuthProviderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Unlink auth provider
     *
     * @generated from rpc api.v1.service.UserService.UnlinkAuthProvider
     */
    unlinkAuthProvider: {
      name: "UnlinkAuthProvider",
      I: UnlinkAuthProviderRequest,
      O: UnlinkAuthProviderResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
