// @generated by protoc-gen-connect-query v2.1.1 with parameter "target=ts"
// @generated from file v1/service/user_service.proto (package api.v1.service, syntax proto3)
/* eslint-disable */

import { UserService } from "./user_service_pb";

/**
 * Get or create anonymous user
 *
 * @generated from rpc api.v1.service.UserService.GetCurrentUser
 */
export const getCurrentUser = UserService.method.getCurrentUser;

/**
 * Convert anonymous to registered user
 *
 * @generated from rpc api.v1.service.UserService.RegisterUser
 */
export const registerUser = UserService.method.registerUser;

/**
 * Get user by ID
 *
 * @generated from rpc api.v1.service.UserService.GetUser
 */
export const getUser = UserService.method.getUser;
