// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file v1/service/user.proto (package api.v1.service, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type {
  GenFile,
  GenMessage,
  GenService,
} from "@bufbuild/protobuf/codegenv2";
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";
import {
  file_google_protobuf_empty,
  file_google_protobuf_field_mask,
} from "@bufbuild/protobuf/wkt";
import type { UserAuthProvider as AuthProvider, User, UserProfile } from "../entities/user_pb";
import { file_v1_entities_user } from "../entities/user_pb";

/**
 * Describes the file v1/service/user.proto.
 */
export const file_v1_service_user: GenFile =
  /*@__PURE__*/
  fileDesc(
    "ChV2MS9zZXJ2aWNlL3VzZXIucHJvdG8SDmFwaS52MS5zZXJ2aWNlIj0KFkdldEN1cnJlbnRVc2VyUmVzcG9uc2USIwoEdXNlchgBIAEoCzIVLmFwaS52MS5lbnRpdGllcy5Vc2VyIiIKDkdldFVzZXJSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJIkAKD0dldFVzZXJSZXNwb25zZRItCgdwcm9maWxlGAEgASgLMhwuYXBpLnYxLmVudGl0aWVzLlVzZXJQcm9maWxlIpsBChRVcGRhdGVQcm9maWxlUmVxdWVzdBIvCgt1cGRhdGVfbWFzaxgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE1hc2sSGQoMZGlzcGxheV9uYW1lGAIgASgJSACIAQESFwoKYXZhdGFyX3VybBgDIAEoCUgBiAEBQg8KDV9kaXNwbGF5X25hbWVCDQoLX2F2YXRhcl91cmwiPAoVVXBkYXRlUHJvZmlsZVJlc3BvbnNlEiMKBHVzZXIYASABKAsyFS5hcGkudjEuZW50aXRpZXMuVXNlciJMChhHZXRBdXRoUHJvdmlkZXJzUmVzcG9uc2USMAoJcHJvdmlkZXJzGAEgAygLMh0uYXBpLnYxLmVudGl0aWVzLkF1dGhQcm92aWRlciI/ChdMaW5rQXV0aFByb3ZpZGVyUmVxdWVzdBIQCghwcm92aWRlchgBIAEoCRISCgpjcmVkZW50aWFsGAIgASgJIkwKGExpbmtBdXRoUHJvdmlkZXJSZXNwb25zZRIwCglwcm92aWRlcnMYASADKAsyHS5hcGkudjEuZW50aXRpZXMuQXV0aFByb3ZpZGVyIi0KGVVubGlua0F1dGhQcm92aWRlclJlcXVlc3QSEAoIcHJvdmlkZXIYASABKAkiTgoaVW5saW5rQXV0aFByb3ZpZGVyUmVzcG9uc2USMAoJcHJvdmlkZXJzGAEgAygLMh0uYXBpLnYxLmVudGl0aWVzLkF1dGhQcm92aWRlcjKzBAoLVXNlclNlcnZpY2USUAoOR2V0Q3VycmVudFVzZXISFi5nb29nbGUucHJvdG9idWYuRW1wdHkaJi5hcGkudjEuc2VydmljZS5HZXRDdXJyZW50VXNlclJlc3BvbnNlEkoKB0dldFVzZXISHi5hcGkudjEuc2VydmljZS5HZXRVc2VyUmVxdWVzdBofLmFwaS52MS5zZXJ2aWNlLkdldFVzZXJSZXNwb25zZRJcCg1VcGRhdGVQcm9maWxlEiQuYXBpLnYxLnNlcnZpY2UuVXBkYXRlUHJvZmlsZVJlcXVlc3QaJS5hcGkudjEuc2VydmljZS5VcGRhdGVQcm9maWxlUmVzcG9uc2USVAoQR2V0QXV0aFByb3ZpZGVycxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRooLmFwaS52MS5zZXJ2aWNlLkdldEF1dGhQcm92aWRlcnNSZXNwb25zZRJlChBMaW5rQXV0aFByb3ZpZGVyEicuYXBpLnYxLnNlcnZpY2UuTGlua0F1dGhQcm92aWRlclJlcXVlc3QaKC5hcGkudjEuc2VydmljZS5MaW5rQXV0aFByb3ZpZGVyUmVzcG9uc2USawoSVW5saW5rQXV0aFByb3ZpZGVyEikuYXBpLnYxLnNlcnZpY2UuVW5saW5rQXV0aFByb3ZpZGVyUmVxdWVzdBoqLmFwaS52MS5zZXJ2aWNlLlVubGlua0F1dGhQcm92aWRlclJlc3BvbnNlQjxaOmdpdGh1Yi5jb20vY2tyd2wvYWx1bmFsdW4vYXBpL2dlbi9hcGkvdjEvc2VydmljZTtzZXJ2aWNldjFiBnByb3RvMw",
    [
      file_v1_entities_user,
      file_google_protobuf_empty,
      file_google_protobuf_field_mask,
    ],
  );

/**
 * GetCurrentUserResponse returns current user
 *
 * @generated from message api.v1.service.GetCurrentUserResponse
 */
export type GetCurrentUserResponse =
  Message<"api.v1.service.GetCurrentUserResponse"> & {
    /**
     * @generated from field: api.v1.entities.User user = 1;
     */
    user?: User;
  };

/**
 * Describes the message api.v1.service.GetCurrentUserResponse.
 * Use `create(GetCurrentUserResponseSchema)` to create a new message.
 */
export const GetCurrentUserResponseSchema: GenMessage<GetCurrentUserResponse> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 0);

/**
 * GetUserRequest by username
 *
 * @generated from message api.v1.service.GetUserRequest
 */
export type GetUserRequest = Message<"api.v1.service.GetUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message api.v1.service.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 1);

/**
 * GetUserResponse returns public profile
 *
 * @generated from message api.v1.service.GetUserResponse
 */
export type GetUserResponse = Message<"api.v1.service.GetUserResponse"> & {
  /**
   * @generated from field: api.v1.entities.UserProfile profile = 1;
   */
  profile?: UserProfile;
};

/**
 * Describes the message api.v1.service.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 2);

/**
 * UpdateProfileRequest updates user profile
 *
 * @generated from message api.v1.service.UpdateProfileRequest
 */
export type UpdateProfileRequest =
  Message<"api.v1.service.UpdateProfileRequest"> & {
    /**
     * @generated from field: google.protobuf.FieldMask update_mask = 1;
     */
    updateMask?: FieldMask;

    /**
     * @generated from field: optional string display_name = 2;
     */
    displayName?: string;

    /**
     * @generated from field: optional string avatar_url = 3;
     */
    avatarUrl?: string;
  };

/**
 * Describes the message api.v1.service.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 3);

/**
 * UpdateProfileResponse returns updated user
 *
 * @generated from message api.v1.service.UpdateProfileResponse
 */
export type UpdateProfileResponse =
  Message<"api.v1.service.UpdateProfileResponse"> & {
    /**
     * @generated from field: api.v1.entities.User user = 1;
     */
    user?: User;
  };

/**
 * Describes the message api.v1.service.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export const UpdateProfileResponseSchema: GenMessage<UpdateProfileResponse> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 4);

/**
 * GetAuthProvidersResponse returns linked providers
 *
 * @generated from message api.v1.service.GetAuthProvidersResponse
 */
export type GetAuthProvidersResponse =
  Message<"api.v1.service.GetAuthProvidersResponse"> & {
    /**
     * @generated from field: repeated api.v1.entities.AuthProvider providers = 1;
     */
    providers: AuthProvider[];
  };

/**
 * Describes the message api.v1.service.GetAuthProvidersResponse.
 * Use `create(GetAuthProvidersResponseSchema)` to create a new message.
 */
export const GetAuthProvidersResponseSchema: GenMessage<GetAuthProvidersResponse> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 5);

/**
 * LinkAuthProviderRequest links new provider
 *
 * @generated from message api.v1.service.LinkAuthProviderRequest
 */
export type LinkAuthProviderRequest =
  Message<"api.v1.service.LinkAuthProviderRequest"> & {
    /**
     * "google", "github", etc
     *
     * @generated from field: string provider = 1;
     */
    provider: string;

    /**
     * OAuth token
     *
     * @generated from field: string credential = 2;
     */
    credential: string;
  };

/**
 * Describes the message api.v1.service.LinkAuthProviderRequest.
 * Use `create(LinkAuthProviderRequestSchema)` to create a new message.
 */
export const LinkAuthProviderRequestSchema: GenMessage<LinkAuthProviderRequest> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 6);

/**
 * LinkAuthProviderResponse returns updated providers
 *
 * @generated from message api.v1.service.LinkAuthProviderResponse
 */
export type LinkAuthProviderResponse =
  Message<"api.v1.service.LinkAuthProviderResponse"> & {
    /**
     * @generated from field: repeated api.v1.entities.AuthProvider providers = 1;
     */
    providers: AuthProvider[];
  };

/**
 * Describes the message api.v1.service.LinkAuthProviderResponse.
 * Use `create(LinkAuthProviderResponseSchema)` to create a new message.
 */
export const LinkAuthProviderResponseSchema: GenMessage<LinkAuthProviderResponse> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 7);

/**
 * UnlinkAuthProviderRequest unlinks provider
 *
 * @generated from message api.v1.service.UnlinkAuthProviderRequest
 */
export type UnlinkAuthProviderRequest =
  Message<"api.v1.service.UnlinkAuthProviderRequest"> & {
    /**
     * @generated from field: string provider = 1;
     */
    provider: string;
  };

/**
 * Describes the message api.v1.service.UnlinkAuthProviderRequest.
 * Use `create(UnlinkAuthProviderRequestSchema)` to create a new message.
 */
export const UnlinkAuthProviderRequestSchema: GenMessage<UnlinkAuthProviderRequest> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 8);

/**
 * UnlinkAuthProviderResponse returns remaining providers
 *
 * @generated from message api.v1.service.UnlinkAuthProviderResponse
 */
export type UnlinkAuthProviderResponse =
  Message<"api.v1.service.UnlinkAuthProviderResponse"> & {
    /**
     * @generated from field: repeated api.v1.entities.AuthProvider providers = 1;
     */
    providers: AuthProvider[];
  };

/**
 * Describes the message api.v1.service.UnlinkAuthProviderResponse.
 * Use `create(UnlinkAuthProviderResponseSchema)` to create a new message.
 */
export const UnlinkAuthProviderResponseSchema: GenMessage<UnlinkAuthProviderResponse> =
  /*@__PURE__*/
  messageDesc(file_v1_service_user, 9);

/**
 * UserService handles user profile management
 *
 * @generated from service api.v1.service.UserService
 */
export const UserService: GenService<{
  /**
   * Get current user profile
   *
   * @generated from rpc api.v1.service.UserService.GetCurrentUser
   */
  getCurrentUser: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetCurrentUserResponseSchema;
  };
  /**
   * Get user by username
   *
   * @generated from rpc api.v1.service.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  };
  /**
   * Update current user profile
   *
   * @generated from rpc api.v1.service.UserService.UpdateProfile
   */
  updateProfile: {
    methodKind: "unary";
    input: typeof UpdateProfileRequestSchema;
    output: typeof UpdateProfileResponseSchema;
  };
  /**
   * Get linked auth providers
   *
   * @generated from rpc api.v1.service.UserService.GetAuthProviders
   */
  getAuthProviders: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetAuthProvidersResponseSchema;
  };
  /**
   * Link new auth provider
   *
   * @generated from rpc api.v1.service.UserService.LinkAuthProvider
   */
  linkAuthProvider: {
    methodKind: "unary";
    input: typeof LinkAuthProviderRequestSchema;
    output: typeof LinkAuthProviderResponseSchema;
  };
  /**
   * Unlink auth provider
   *
   * @generated from rpc api.v1.service.UserService.UnlinkAuthProvider
   */
  unlinkAuthProvider: {
    methodKind: "unary";
    input: typeof UnlinkAuthProviderRequestSchema;
    output: typeof UnlinkAuthProviderResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_v1_service_user, 0);
