// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file v1/service/user_service.proto (package api.v1.service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "../entities/user_pb";
import { file_v1_entities_user } from "../entities/user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/service/user_service.proto.
 */
export const file_v1_service_user_service: GenFile = /*@__PURE__*/
  fileDesc("Ch12MS9zZXJ2aWNlL3VzZXJfc2VydmljZS5wcm90bxIOYXBpLnYxLnNlcnZpY2UiFwoVR2V0Q3VycmVudFVzZXJSZXF1ZXN0IlMKFkdldEN1cnJlbnRVc2VyUmVzcG9uc2USIwoEdXNlchgBIAEoCzIVLmFwaS52MS5lbnRpdGllcy5Vc2VyEhQKDGFjY2Vzc190b2tlbhgCIAEoCSJIChNSZWdpc3RlclVzZXJSZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHVzZXJuYW1lGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJIlEKFFJlZ2lzdGVyVXNlclJlc3BvbnNlEiMKBHVzZXIYASABKAsyFS5hcGkudjEuZW50aXRpZXMuVXNlchIUCgxhY2Nlc3NfdG9rZW4YAiABKAkiIQoOR2V0VXNlclJlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCSI2Cg9HZXRVc2VyUmVzcG9uc2USIwoEdXNlchgBIAEoCzIVLmFwaS52MS5lbnRpdGllcy5Vc2VyMpUCCgtVc2VyU2VydmljZRJfCg5HZXRDdXJyZW50VXNlchIlLmFwaS52MS5zZXJ2aWNlLkdldEN1cnJlbnRVc2VyUmVxdWVzdBomLmFwaS52MS5zZXJ2aWNlLkdldEN1cnJlbnRVc2VyUmVzcG9uc2USWQoMUmVnaXN0ZXJVc2VyEiMuYXBpLnYxLnNlcnZpY2UuUmVnaXN0ZXJVc2VyUmVxdWVzdBokLmFwaS52MS5zZXJ2aWNlLlJlZ2lzdGVyVXNlclJlc3BvbnNlEkoKB0dldFVzZXISHi5hcGkudjEuc2VydmljZS5HZXRVc2VyUmVxdWVzdBofLmFwaS52MS5zZXJ2aWNlLkdldFVzZXJSZXNwb25zZUJNWktnaXRodWIuY29tL3JhZGphdGhhaGVyL2FsdW5hbHVuL2FwaS9pbnRlcm5hbC9wcm90b2NnZW4vdjEvc2VydmljZTtzZXJ2aWNldjFiBnByb3RvMw", [file_v1_entities_user]);

/**
 * GetCurrentUserRequest - empty, uses session/JWT context
 *
 * @generated from message api.v1.service.GetCurrentUserRequest
 */
export type GetCurrentUserRequest = Message<"api.v1.service.GetCurrentUserRequest"> & {
};

/**
 * Describes the message api.v1.service.GetCurrentUserRequest.
 * Use `create(GetCurrentUserRequestSchema)` to create a new message.
 */
export const GetCurrentUserRequestSchema: GenMessage<GetCurrentUserRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_user_service, 0);

/**
 * @generated from message api.v1.service.GetCurrentUserResponse
 */
export type GetCurrentUserResponse = Message<"api.v1.service.GetCurrentUserResponse"> & {
  /**
   * @generated from field: api.v1.entities.User user = 1;
   */
  user?: User;

  /**
   * JWT for anonymous/registered user
   *
   * @generated from field: string access_token = 2;
   */
  accessToken: string;
};

/**
 * Describes the message api.v1.service.GetCurrentUserResponse.
 * Use `create(GetCurrentUserResponseSchema)` to create a new message.
 */
export const GetCurrentUserResponseSchema: GenMessage<GetCurrentUserResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_user_service, 1);

/**
 * @generated from message api.v1.service.RegisterUserRequest
 */
export type RegisterUserRequest = Message<"api.v1.service.RegisterUserRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * For password provider
   *
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message api.v1.service.RegisterUserRequest.
 * Use `create(RegisterUserRequestSchema)` to create a new message.
 */
export const RegisterUserRequestSchema: GenMessage<RegisterUserRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_user_service, 2);

/**
 * @generated from message api.v1.service.RegisterUserResponse
 */
export type RegisterUserResponse = Message<"api.v1.service.RegisterUserResponse"> & {
  /**
   * @generated from field: api.v1.entities.User user = 1;
   */
  user?: User;

  /**
   * New JWT with registered user claims
   *
   * @generated from field: string access_token = 2;
   */
  accessToken: string;
};

/**
 * Describes the message api.v1.service.RegisterUserResponse.
 * Use `create(RegisterUserResponseSchema)` to create a new message.
 */
export const RegisterUserResponseSchema: GenMessage<RegisterUserResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_user_service, 3);

/**
 * @generated from message api.v1.service.GetUserRequest
 */
export type GetUserRequest = Message<"api.v1.service.GetUserRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message api.v1.service.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_v1_service_user_service, 4);

/**
 * @generated from message api.v1.service.GetUserResponse
 */
export type GetUserResponse = Message<"api.v1.service.GetUserResponse"> & {
  /**
   * @generated from field: api.v1.entities.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message api.v1.service.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_v1_service_user_service, 5);

/**
 * UserService handles user-related operations
 *
 * @generated from service api.v1.service.UserService
 */
export const UserService: GenService<{
  /**
   * Get or create anonymous user
   *
   * @generated from rpc api.v1.service.UserService.GetCurrentUser
   */
  getCurrentUser: {
    methodKind: "unary";
    input: typeof GetCurrentUserRequestSchema;
    output: typeof GetCurrentUserResponseSchema;
  },
  /**
   * Convert anonymous to registered user
   *
   * @generated from rpc api.v1.service.UserService.RegisterUser
   */
  registerUser: {
    methodKind: "unary";
    input: typeof RegisterUserRequestSchema;
    output: typeof RegisterUserResponseSchema;
  },
  /**
   * Get user by ID
   *
   * @generated from rpc api.v1.service.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_v1_service_user_service, 0);

