// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file models/user.proto (package api.models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file models/user.proto.
 */
export const file_models_user: GenFile = /*@__PURE__*/
  fileDesc("ChFtb2RlbHMvdXNlci5wcm90bxIKYXBpLm1vZGVscyJqCgRVc2VyEgoKAmlkGAEgASgJEhIKBWVtYWlsGAIgASgJSACIAQESEAoIdXNlcm5hbWUYAyABKAkSEgoKY3JlYXRlZF9hdBgEIAEoAxISCgp1cGRhdGVkX2F0GAUgASgDQggKBl9lbWFpbCKRAQoQVXNlckF1dGhQcm92aWRlchIKCgJpZBgBIAEoCRIPCgd1c2VyX2lkGAIgASgJEhAKCHByb3ZpZGVyGAMgASgJEhgKEHByb3ZpZGVyX3VzZXJfaWQYBCABKAkSDAoEZGF0YRgFIAEoDBISCgpjcmVhdGVkX2F0GAYgASgDEhIKCnVwZGF0ZWRfYXQYByABKAMi7gEKC1VzZXJQcm9maWxlEg8KB3VzZXJfaWQYASABKAkSFwoKZmlyc3RfbmFtZRgCIAEoCUgAiAEBEhYKCWxhc3RfbmFtZRgDIAEoCUgBiAEBEhcKCmF2YXRhcl91cmwYBCABKAlIAogBARIQCgNiaW8YBSABKAlIA4gBARIWCg5lbWFpbF92ZXJpZmllZBgGIAEoCBISCgpjcmVhdGVkX2F0GAcgASgDEhIKCnVwZGF0ZWRfYXQYCCABKANCDQoLX2ZpcnN0X25hbWVCDAoKX2xhc3RfbmFtZUINCgtfYXZhdGFyX3VybEIGCgRfYmlvQkZaRGdpdGh1Yi5jb20vcmFkamF0aGFoZXIvYWx1bmFsdW4vYXBpL2ludGVybmFsL3Byb3RvY2dlbi9tb2RlbHM7bW9kZWxzYgZwcm90bzM");

/**
 * User model matching database schema
 *
 * @generated from message api.models.User
 */
export type User = Message<"api.models.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * NULL for anonymous
   *
   * @generated from field: optional string email = 2;
   */
  email?: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: int64 created_at = 4;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 updated_at = 5;
   */
  updatedAt: bigint;
};

/**
 * Describes the message api.models.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_models_user, 0);

/**
 * @generated from message api.models.UserAuthProvider
 */
export type UserAuthProvider = Message<"api.models.UserAuthProvider"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: string provider = 3;
   */
  provider: string;

  /**
   * @generated from field: string provider_user_id = 4;
   */
  providerUserId: string;

  /**
   * JSON data
   *
   * @generated from field: bytes data = 5;
   */
  data: Uint8Array;

  /**
   * @generated from field: int64 created_at = 6;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 updated_at = 7;
   */
  updatedAt: bigint;
};

/**
 * Describes the message api.models.UserAuthProvider.
 * Use `create(UserAuthProviderSchema)` to create a new message.
 */
export const UserAuthProviderSchema: GenMessage<UserAuthProvider> = /*@__PURE__*/
  messageDesc(file_models_user, 1);

/**
 * @generated from message api.models.UserProfile
 */
export type UserProfile = Message<"api.models.UserProfile"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: optional string first_name = 2;
   */
  firstName?: string;

  /**
   * @generated from field: optional string last_name = 3;
   */
  lastName?: string;

  /**
   * @generated from field: optional string avatar_url = 4;
   */
  avatarUrl?: string;

  /**
   * @generated from field: optional string bio = 5;
   */
  bio?: string;

  /**
   * @generated from field: bool email_verified = 6;
   */
  emailVerified: boolean;

  /**
   * @generated from field: int64 created_at = 7;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 updated_at = 8;
   */
  updatedAt: bigint;
};

/**
 * Describes the message api.models.UserProfile.
 * Use `create(UserProfileSchema)` to create a new message.
 */
export const UserProfileSchema: GenMessage<UserProfile> = /*@__PURE__*/
  messageDesc(file_models_user, 2);

